### ISSUE TITLE
Supported color formats

### ISSUE THREAD

**Issue by Selur** [dubhater/vapoursynth-awarpsharp2#2]
> Clip to process. Must be 8..16 bit, not RGB, with constant format and dimensions.

Do I get this right?
Looking at the Vapoursynth color formats (http://www.vapoursynth.com/doc/pythonreference.html#format-constants)

> GRAY8
> GRAY16
> GRAYH
> GRAYS
> 
> YUV420P8
> YUV422P8
> YUV444P8
> YUV410P8
> YUV411P8
> YUV440P8
> 
> YUV420P9
> YUV422P9
> YUV444P9
> 
> YUV420P10
> YUV422P10
> YUV444P10
> 
> YUV420P16
> YUV422P16
> YUV444P16
> 
> YUV444PH
> YUV444PS
> 
> COMPATYUY2

are all supported?

**Comment by dubhater** [comment]
Not quite.
1. No third-party filters are allowed to process compat formats, only some filters built into the VapourSynth core. Those formats only exist in VapourSynth because some Avisynth plugins use them.
2. The "8..16 bit" part excludes the H (half precision float) and S (single precision float) formats. It should really say "8..16 bit integer".

**Comment by Selur** [comment]
Thanks for the explanation!
so it's:

> GRAY8
> GRAY16
> 
> YUV420P8
> YUV422P8
> YUV444P8
> YUV410P8
> YUV411P8
> YUV440P8
> 
> YUV420P9
> YUV422P9
> YUV444P9
> 
> YUV420P10
> YUV422P10
> YUV444P10
> 
> YUV420P16
> YUV422P16
> YUV444P16

**Comment by dubhater** [comment]
Yes, but that's really a subset of what's supported. You can have clips with less common bit depths, like 11. In other filters (not Awarpsharp2) you can also have weirder chroma subsampling schemes not covered by that list.

**Comment by dubhater** [comment]
Actually I think this filter will reject 4:1:0 and 4:1:1.

**Comment by Selur** [comment]
> In other filters (not Awarpsharp2) you can also have weirder chroma subsampling schemes not covered by that list.

I though those were the only color formats supported by Vapoursynth.

> Actually I think this filter will reject 4:1:0 and 4:1:1.

Okay, that leaves:

> GRAY8
>  GRAY16
> 
> YUV420P8
> YUV422P8
> YUV444P8
> YUV440P8
> 
> YUV420P9
> YUV422P9
> YUV444P9
> 
> YUV420P10
> YUV422P10
> YUV444P10
> 
> YUV420P16
> YUV422P16
> YUV444P16

**Comment by dubhater** [comment]
> I though those were the only color formats supported by Vapoursynth.

No, those are merely predefined constants for the commonly used formats. See the register_format function somewhere above that list.

**Comment by Selur** [comment]
Ah, missed that. :) Thanks again for the help and explanation!
